---
# terraform init -input=false
# terraform apply -input=false -auto-approve
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  runProject:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules
            - run: npm start
  deploy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init -input=false
      - run: terraform apply -input=false -auto-approve
workflows:
  version: 2
  myPizza:
    jobs:
      - runProject
      - deploy:
          requires:
            - runProject
          filters:
            branches:
              only: master