---
# terraform init -input=false
# terraform apply -input=false -auto-approve
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  runProject:
    environment:
      NOMENEGOCIO: "Joao Camargo"
      DATABASE_ID: "86c8f911-df15-432b-831d-51f9407bcb95"
      DATABASE_TOKEN: "03494566-4b7c-4935-8662-ed42761be154"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: "Update npm"
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules
            - run:
                name: "Deveria rodar testes na aplicação"
                command: "echo 'Ainda nao escrevi eles'"
            - store_artifacts:
                path: test-results

            - store_test_results:
                path: test-results
  deploy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init -input=false
      - run: terraform apply -input=false -auto-approve
workflows:
  myPizza:
    jobs:
      - runProject
      - deploy:
          requires:
            - runProject
          filters:
            branches:
              only: master